name: nearby_pg
description: Find Your Perfect PG - Premium PG Discovery Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  cached_network_image: ^3.3.0
  card_swiper: ^3.0.1
  carousel_slider: ^4.2.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  go_router: ^16.0.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  lottie: ^2.7.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  share_plus: ^11.0.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
