name: nearby_pg
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  geocoding: ^2.1.0
  geolocator: ^10.1.0
  go_router: ^10.1.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^2.7.0
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true